/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_fenetre_ajout (void)
{
  GtkWidget *fenetre_ajout;
  GtkWidget *fixed1;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *type;
  GtkWidget *label3;
  GtkWidget *marque;
  GtkWidget *label4;
  GtkWidget *puissance;
  GtkWidget *label5;
  GtkWidget *annee;
  GtkWidget *label6;
  GtkWidget *matricule;
  GtkWidget *ajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label7;
  GtkWidget *ann_ajout_gp;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label23;
  GtkWidget *Ret_aj_aff_gp;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label22;
  GtkWidget *label29;

  fenetre_ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_ajout), _("Ajouter"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (fenetre_ajout), fixed1);

  label1 = gtk_label_new (_("Ajouter un nouvel equipement"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 72, 16);
  gtk_widget_set_size_request (label1, 248, 16);

  label2 = gtk_label_new (_("Type :"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 40, 64);
  gtk_widget_set_size_request (label2, 72, 16);

  type = gtk_entry_new ();
  gtk_widget_show (type);
  gtk_fixed_put (GTK_FIXED (fixed1), type, 160, 56);
  gtk_widget_set_size_request (type, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (type), 8226);

  label3 = gtk_label_new (_("Marque :"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 40, 112);
  gtk_widget_set_size_request (label3, 80, 16);

  marque = gtk_entry_new ();
  gtk_widget_show (marque);
  gtk_fixed_put (GTK_FIXED (fixed1), marque, 160, 104);
  gtk_widget_set_size_request (marque, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (marque), 8226);

  label4 = gtk_label_new (_("Puissance :"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 40, 160);
  gtk_widget_set_size_request (label4, 88, 16);

  puissance = gtk_entry_new ();
  gtk_widget_show (puissance);
  gtk_fixed_put (GTK_FIXED (fixed1), puissance, 160, 152);
  gtk_widget_set_size_request (puissance, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (puissance), 8226);

  label5 = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 48, 208);
  gtk_widget_set_size_request (label5, 72, 16);

  annee = gtk_entry_new ();
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed1), annee, 160, 200);
  gtk_widget_set_size_request (annee, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (annee), 8226);

  label6 = gtk_label_new (_("Matricule :"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 32, 256);
  gtk_widget_set_size_request (label6, 104, 16);

  matricule = gtk_entry_new ();
  gtk_widget_show (matricule);
  gtk_fixed_put (GTK_FIXED (fixed1), matricule, 160, 248);
  gtk_widget_set_size_request (matricule, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (matricule), 8226);

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter, 96, 304);
  gtk_widget_set_size_request (ajouter, 88, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox1), label7, FALSE, FALSE, 0);

  ann_ajout_gp = gtk_button_new ();
  gtk_widget_show (ann_ajout_gp);
  gtk_fixed_put (GTK_FIXED (fixed1), ann_ajout_gp, 256, 304);
  gtk_widget_set_size_request (ann_ajout_gp, 88, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (ann_ajout_gp), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox7), label23, FALSE, FALSE, 0);

  Ret_aj_aff_gp = gtk_button_new ();
  gtk_widget_show (Ret_aj_aff_gp);
  gtk_fixed_put (GTK_FIXED (fixed1), Ret_aj_aff_gp, 168, 424);
  gtk_widget_set_size_request (Ret_aj_aff_gp, 104, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (Ret_aj_aff_gp), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox6), label22, FALSE, FALSE, 0);

  label29 = gtk_label_new ("");
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed1), label29, 136, 352);
  gtk_widget_set_size_request (label29, 208, 32);

  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) ann_ajout_gp, "clicked",
                    G_CALLBACK (on_ann_ajout_gp_clicked),
                    NULL);
  g_signal_connect ((gpointer) Ret_aj_aff_gp, "clicked",
                    G_CALLBACK (on_Ret_aj_aff_gp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_ajout, fenetre_ajout, "fenetre_ajout");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label1, "label1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label2, "label2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, type, "type");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label3, "label3");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, marque, "marque");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label4, "label4");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, puissance, "puissance");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label5, "label5");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, annee, "annee");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label6, "label6");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, matricule, "matricule");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, image1, "image1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label7, "label7");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, ann_ajout_gp, "ann_ajout_gp");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, image7, "image7");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label23, "label23");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, Ret_aj_aff_gp, "Ret_aj_aff_gp");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, image6, "image6");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label22, "label22");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label29, "label29");

  return fenetre_ajout;
}

GtkWidget*
create_fenetre_afficher (void)
{
  GtkWidget *fenetre_afficher;
  GtkWidget *fixed2;
  GtkWidget *label9;
  GtkWidget *treeview1;
  GtkWidget *notebook1;
  GtkWidget *fixed3;
  GtkWidget *matricule_modifier;
  GtkWidget *modifier;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label13;
  GtkWidget *label12;
  GtkWidget *label10;
  GtkWidget *fixed4;
  GtkWidget *label14;
  GtkWidget *matricule_supprimer;
  GtkWidget *label25;
  GtkWidget *supprimer;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label15;
  GtkWidget *label30;
  GtkWidget *label11;
  GtkWidget *Affich_gp;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label24;
  GtkWidget *go_to_ajout_gp;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label28;

  fenetre_afficher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_afficher), _("Afficher"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (fenetre_afficher), fixed2);

  label9 = gtk_label_new (_("Afficher les equipements disponibles"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 40, 32);
  gtk_widget_set_size_request (label9, 312, 16);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 48, 56);
  gtk_widget_set_size_request (treeview1, 440, 120);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed2), notebook1, 40, 264);
  gtk_widget_set_size_request (notebook1, 456, 232);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  matricule_modifier = gtk_entry_new ();
  gtk_widget_show (matricule_modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), matricule_modifier, 64, 48);
  gtk_widget_set_size_request (matricule_modifier, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (matricule_modifier), 8226);

  modifier = gtk_button_new ();
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), modifier, 104, 104);
  gtk_widget_set_size_request (modifier, 88, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (modifier), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox3), label13, FALSE, FALSE, 0);

  label12 = gtk_label_new (_("Donner la matricule a modifier"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed3), label12, 0, 16);
  gtk_widget_set_size_request (label12, 288, 16);

  label10 = gtk_label_new (_("Modifier"));
  gtk_widget_show (label10);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label10);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  label14 = gtk_label_new (_("Donner la matricule a supprimer"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed4), label14, 8, 24);
  gtk_widget_set_size_request (label14, 288, 16);

  matricule_supprimer = gtk_entry_new ();
  gtk_widget_show (matricule_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed4), matricule_supprimer, 64, 56);
  gtk_widget_set_size_request (matricule_supprimer, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (matricule_supprimer), 8226);

  label25 = gtk_label_new ("");
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 32, 184);
  gtk_widget_set_size_request (label25, 264, 16);

  supprimer = gtk_button_new ();
  gtk_widget_show (supprimer);
  gtk_fixed_put (GTK_FIXED (fixed4), supprimer, 96, 120);
  gtk_widget_set_size_request (supprimer, 112, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (supprimer), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox4), label15, FALSE, FALSE, 0);

  label30 = gtk_label_new ("");
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed4), label30, 88, 160);
  gtk_widget_set_size_request (label30, 232, 16);

  label11 = gtk_label_new (_("Supprimer"));
  gtk_widget_show (label11);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label11);

  Affich_gp = gtk_button_new ();
  gtk_widget_show (Affich_gp);
  gtk_fixed_put (GTK_FIXED (fixed2), Affich_gp, 112, 200);
  gtk_widget_set_size_request (Affich_gp, 120, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (Affich_gp), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-justify-right", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox8), label24, FALSE, FALSE, 0);

  go_to_ajout_gp = gtk_button_new ();
  gtk_widget_show (go_to_ajout_gp);
  gtk_fixed_put (GTK_FIXED (fixed2), go_to_ajout_gp, 336, 200);
  gtk_widget_set_size_request (go_to_ajout_gp, 88, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (go_to_ajout_gp), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox11), label28, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer, "clicked",
                    G_CALLBACK (on_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) Affich_gp, "clicked",
                    G_CALLBACK (on_Affich_gp_clicked),
                    NULL);
  g_signal_connect ((gpointer) go_to_ajout_gp, "clicked",
                    G_CALLBACK (on_go_to_ajout_gp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_afficher, fenetre_afficher, "fenetre_afficher");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label9, "label9");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, matricule_modifier, "matricule_modifier");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image3, "image3");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label13, "label13");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label12, "label12");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label10, "label10");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label14, "label14");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, matricule_supprimer, "matricule_supprimer");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label25, "label25");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image4, "image4");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label15, "label15");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label30, "label30");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label11, "label11");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, Affich_gp, "Affich_gp");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image8, "image8");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label24, "label24");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, go_to_ajout_gp, "go_to_ajout_gp");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image11, "image11");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label28, "label28");

  return fenetre_afficher;
}

GtkWidget*
create_fenetre_modifier (void)
{
  GtkWidget *fenetre_modifier;
  GtkWidget *fixed5;
  GtkWidget *label20;
  GtkWidget *label19;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *modifier_type;
  GtkWidget *modifier_marque;
  GtkWidget *modifier_puissance;
  GtkWidget *modifier_annee;
  GtkWidget *ann_modif_gp;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label26;
  GtkWidget *ok;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label21;
  GtkWidget *ret_aff_mod_gp;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label27;
  GtkWidget *label31;
  GtkWidget *label16;
  GtkWidget *modifier_matri;
  GtkWidget *label32;

  fenetre_modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_modifier), _("Afficher"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (fenetre_modifier), fixed5);

  label20 = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed5), label20, 24, 232);
  gtk_widget_set_size_request (label20, 112, 16);

  label19 = gtk_label_new (_("Puissance :"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed5), label19, 40, 184);
  gtk_widget_set_size_request (label19, 96, 16);

  label17 = gtk_label_new (_("Type :"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed5), label17, 24, 96);
  gtk_widget_set_size_request (label17, 96, 16);

  label18 = gtk_label_new (_("Marque :"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed5), label18, 16, 136);
  gtk_widget_set_size_request (label18, 104, 16);

  modifier_type = gtk_entry_new ();
  gtk_widget_show (modifier_type);
  gtk_fixed_put (GTK_FIXED (fixed5), modifier_type, 160, 88);
  gtk_widget_set_size_request (modifier_type, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modifier_type), 8226);

  modifier_marque = gtk_entry_new ();
  gtk_widget_show (modifier_marque);
  gtk_fixed_put (GTK_FIXED (fixed5), modifier_marque, 160, 136);
  gtk_widget_set_size_request (modifier_marque, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modifier_marque), 8226);

  modifier_puissance = gtk_entry_new ();
  gtk_widget_show (modifier_puissance);
  gtk_fixed_put (GTK_FIXED (fixed5), modifier_puissance, 160, 184);
  gtk_widget_set_size_request (modifier_puissance, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modifier_puissance), 8226);

  modifier_annee = gtk_entry_new ();
  gtk_widget_show (modifier_annee);
  gtk_fixed_put (GTK_FIXED (fixed5), modifier_annee, 160, 232);
  gtk_widget_set_size_request (modifier_annee, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modifier_annee), 8226);

  ann_modif_gp = gtk_button_new ();
  gtk_widget_show (ann_modif_gp);
  gtk_fixed_put (GTK_FIXED (fixed5), ann_modif_gp, 280, 288);
  gtk_widget_set_size_request (ann_modif_gp, 80, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (ann_modif_gp), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox9), label26, FALSE, FALSE, 0);

  ok = gtk_button_new ();
  gtk_widget_show (ok);
  gtk_fixed_put (GTK_FIXED (fixed5), ok, 152, 288);
  gtk_widget_set_size_request (ok, 72, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (ok), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Ok"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox5), label21, FALSE, FALSE, 0);

  ret_aff_mod_gp = gtk_button_new ();
  gtk_widget_show (ret_aff_mod_gp);
  gtk_fixed_put (GTK_FIXED (fixed5), ret_aff_mod_gp, 48, 376);
  gtk_widget_set_size_request (ret_aff_mod_gp, 80, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (ret_aff_mod_gp), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox10), label27, FALSE, FALSE, 0);

  label31 = gtk_label_new ("");
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed5), label31, 136, 336);
  gtk_widget_set_size_request (label31, 248, 24);

  label16 = gtk_label_new (_("Modifier un equipement"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed5), label16, 64, 8);
  gtk_widget_set_size_request (label16, 296, 16);

  modifier_matri = gtk_entry_new ();
  gtk_widget_show (modifier_matri);
  gtk_fixed_put (GTK_FIXED (fixed5), modifier_matri, 160, 48);
  gtk_widget_set_size_request (modifier_matri, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modifier_matri), 8226);

  label32 = gtk_label_new (_("matricule "));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed5), label32, 48, 48);
  gtk_widget_set_size_request (label32, 88, 24);

  g_signal_connect ((gpointer) ann_modif_gp, "clicked",
                    G_CALLBACK (on_ann_modif_gp_clicked),
                    NULL);
  g_signal_connect ((gpointer) ok, "clicked",
                    G_CALLBACK (on_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) ret_aff_mod_gp, "clicked",
                    G_CALLBACK (on_ret_aff_mod_gp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_modifier, fenetre_modifier, "fenetre_modifier");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label20, "label20");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label19, "label19");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label17, "label17");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label18, "label18");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, modifier_type, "modifier_type");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, modifier_marque, "modifier_marque");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, modifier_puissance, "modifier_puissance");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, modifier_annee, "modifier_annee");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, ann_modif_gp, "ann_modif_gp");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, image9, "image9");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label26, "label26");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, ok, "ok");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, image5, "image5");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label21, "label21");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, ret_aff_mod_gp, "ret_aff_mod_gp");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, image10, "image10");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label27, "label27");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label31, "label31");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label16, "label16");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, modifier_matri, "modifier_matri");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label32, "label32");

  return fenetre_modifier;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed6;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *button1;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label37;
  GtkWidget *button2;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label38;
  GtkWidget *button3;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label39;
  GtkWidget *label40;
  GtkWidget *label41;
  GtkWidget *entry5;
  GtkWidget *label42;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window1), fixed6);

  label33 = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed6), label33, 24, 232);
  gtk_widget_set_size_request (label33, 112, 16);

  label34 = gtk_label_new (_("Puissance :"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed6), label34, 40, 184);
  gtk_widget_set_size_request (label34, 96, 16);

  label35 = gtk_label_new (_("Type :"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed6), label35, 24, 96);
  gtk_widget_set_size_request (label35, 96, 16);

  label36 = gtk_label_new (_("Marque :"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed6), label36, 16, 136);
  gtk_widget_set_size_request (label36, 104, 16);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed6), entry1, 160, 88);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed6), entry2, 160, 136);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed6), entry3, 160, 184);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed6), entry4, 160, 232);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed6), button1, 280, 288);
  gtk_widget_set_size_request (button1, 80, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button1), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox12), label37, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed6), button2, 152, 288);
  gtk_widget_set_size_request (button2, 72, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button2), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Ok"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox13), label38, FALSE, FALSE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed6), button3, 48, 376);
  gtk_widget_set_size_request (button3, 80, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button3), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox14), label39, FALSE, FALSE, 0);

  label40 = gtk_label_new ("");
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed6), label40, 136, 336);
  gtk_widget_set_size_request (label40, 248, 24);

  label41 = gtk_label_new (_("Modifier un equipement"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed6), label41, 64, 8);
  gtk_widget_set_size_request (label41, 296, 16);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed6), entry5, 160, 48);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  label42 = gtk_label_new (_("matricule "));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed6), label42, 48, 48);
  gtk_widget_set_size_request (label42, 88, 24);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_ann_modif_gp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_ret_aff_mod_gp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window1, label33, "label33");
  GLADE_HOOKUP_OBJECT (window1, label34, "label34");
  GLADE_HOOKUP_OBJECT (window1, label35, "label35");
  GLADE_HOOKUP_OBJECT (window1, label36, "label36");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window1, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window1, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window1, image12, "image12");
  GLADE_HOOKUP_OBJECT (window1, label37, "label37");
  GLADE_HOOKUP_OBJECT (window1, button2, "button2");
  GLADE_HOOKUP_OBJECT (window1, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window1, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window1, image13, "image13");
  GLADE_HOOKUP_OBJECT (window1, label38, "label38");
  GLADE_HOOKUP_OBJECT (window1, button3, "button3");
  GLADE_HOOKUP_OBJECT (window1, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window1, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window1, image14, "image14");
  GLADE_HOOKUP_OBJECT (window1, label39, "label39");
  GLADE_HOOKUP_OBJECT (window1, label40, "label40");
  GLADE_HOOKUP_OBJECT (window1, label41, "label41");
  GLADE_HOOKUP_OBJECT (window1, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window1, label42, "label42");

  return window1;
}

